version: '3.8'

services:
  navak-backend:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: navak-backend-single
    restart: always
    ports:
      - "3000:3000" 
    env_file:
      - ./.env
    volumes:
      - ./server/data:/app/server/data
      - ./downloads:/app/downloads 


